---
title: "Response to reviewers for Transl Psych 2025"
author: "Rachel L Smith"
output: pdf_document
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(fig.width = 2.5, fig.height = 2, collapse = TRUE, warning = FALSE, message = FALSE, echo = FALSE)

## Set paths and load data
base_dir <- "~/Documents/PhD/projects/sgacc_wgcna_grcca/"
figures_dir <- paste0(base_dir, "outputs/figures/response_to_reviewers/")
#tables_dir <- paste0(base_dir, "outputs/tables/")
analysis_objects_dir <- paste0(base_dir, "outputs/objects/")

source(paste0(base_dir, "scripts/load_WGCNA_res.R"))

## Load data objects for plots
objects <- list.files(analysis_objects_dir)
objects <- objects[!str_detect(objects, "null|archive")]
for (obj in objects){
  print(paste0("loading ", obj, "...."))
  load(paste0(analysis_objects_dir, obj))
}
```


### R2 Comment 1: Limma vs DESeq2

A. Correlation between Limma and DESeq2 results
```{r R2.C1}
df_de_res_all %>% 
    filter(metric == "l2fc") %>% 
    
    ggplot(aes(x = DESeq2, y = Limma)) +
    geom_hline(yintercept = 0, color = "gray") +
    geom_vline(xintercept = 0, color = "gray") +
    geom_abline(lty = 2) +
    geom_point(aes(color = DESeq2 + Limma), size = 0.75) +
    geom_smooth(method = "lm", linewidth = 0.5, color = "black") +
    stat_cor(label.sep = "\n") +
    #facet_wrap(vars(metric), scales = "free") +
    scale_color_gradientn(colors = rev(brewer.rdbu(100)), guide = "none") +
    labs(
        x = "DESeq2 L2FC", y = "Limma L2FC",
        title = "DESeq2 vs Limma-voom"
    )
map(
  .x = c(".png", ".pdf"),
  .f = ~ ggsave(paste0(figures_dir, "R2C1a.deseq2_vs_limmavoom", .x), width = 2.5, height = 2.0)
)

```

See Figure 4 v2 markdown file for redo Figure 4 using Limma instead of DESeq2

Fig S9.

### A | Venn diagram of significant DEG overlap

```{r FigS9a.prep}
## Venn diagram (overlap with Nirmala's results)
my_degs <- df_limma_res %>% dplyr::filter(p_value < 0.05) %>% pull(ensembl_gene_id)
length(my_degs) # N = 1389

akula_degs <- df_akula_res %>% 
    dplyr::filter(pvalue < 0.05) %>% 
    pull(ensembl_gene_id)
length(akula_degs) # N = 1373

sig_grcca_genes <- df_x_res %>% 
    dplyr::filter(p_adj < 0.05 & abs(z_score) > 2) %>% 
    pull(ensembl_gene_id)
length(sig_grcca_genes) # N = 1211

# Akula DEGs vs my DEGs
hypergeometric_overlap <- f_hypergeometric(my_degs, akula_degs, gene_universe = ensembl_gene_ids)
length(hypergeometric_overlap$overlap_genes) # N = 385; P = 1.9*10^-145; OR = 7.17

# GRCCA vs my DEGs
hypergeometric_overlap <- f_hypergeometric(my_degs, sig_grcca_genes, gene_universe = ensembl_gene_ids)
length(hypergeometric_overlap$overlap_genes) # N = 203; P = 1.5*10^-29; OR = 2.77

# GRCCA vs Akula DEGs
hypergeometric_overlap <- f_hypergeometric(akula_degs, sig_grcca_genes, gene_universe = ensembl_gene_ids)
length(hypergeometric_overlap$overlap_genes) # N = 285; P = 2.3*10^-85; OR = 5.19

# Combine the data into a named list for ggvenn
FigS9a_data <- list(
  `Current study DEGs` = my_degs,
  `Akula et al 2021 DEGs` = akula_degs,
  `Significant GRCCA genes` = sig_grcca_genes
)
```

```{r FigS9a.plot}
ggvenn(
    FigS9a_data, 
    fill_color = c("#E0E0E0", "#E0E0E0", "#E0E0E0"),
    stroke_size = 0.75,
    text_size = 3,
    set_name_size = 4,
    show_percentage = FALSE
) +
    coord_fixed(clip = "off") +
    theme_void() +
    theme(
        text = element_text(size = 8)
    )
map(
  .x = c(".png", ".pdf"),
  .f = ~ ggsave(paste0(figures_dir, "S9A.DEG_GRCCA_venn_diagram", .x), width = fig_width, height = fig_height)
)
```


### B | Correlation plot of L2FC

```{r FigS9b.stats}

### PERMUTE L2FC CORRELATION ###
n_perm <- 10000
df_limma_akula_cor_perm <- tibble()
set.seed(0406)
for (i in 1:n_perm) {
    
    if (i %% 100 == 0) {print(paste0("Running permutation ", i))}
    
    # Permute LFC within module
    df_tmp <- df_de_res_all %>% 
        left_join(df_modules_filt) %>%
        filter(!is.na(Akula) & metric == "l2fc") %>% 
        group_by(module) %>%
        mutate(permuted_l2fc = sample(Limma, replace = FALSE))
    
    # Calculate correlation between permuted data and Nirmala's LFC
    test <- cor.test(df_tmp$permuted_l2fc, df_tmp$Akula)
    correlation <- test$estimate
    p_value <- test$p.value

    # Append to tibble
    df_limma_akula_cor_perm <- df_limma_akula_cor_perm %>% 
        bind_rows(
            tibble(
                perm = i,
                correlation = correlation,
                p_value = p_value
            )
        )
    
}

## Calculate permutation p-values
de_limma_akula_perm_p <- df_limma_akula_cor_perm %>% 
    mutate(obs_corr = cor.test(
        df_de_res_all %>% filter(!is.na(Akula) & metric == "l2fc") %>% pull(Limma), 
        df_de_res_all %>% filter(!is.na(Akula) & metric == "l2fc") %>% pull(Akula), 
        )$estimate
    ) %>%
    summarise(
        perm_p = (sum(abs(correlation) >= abs(obs_corr)) + 1) / (n_perm + 1)
    )
#Pperm=1*10^-4


### PERMUTE T-STAT CORRELATION ###
n_perm <- 10000
df_limma_akula_cor_perm <- tibble()
set.seed(0406)
for (i in 1:n_perm) {
    
    if (i %% 100 == 0) {print(paste0("Running permutation ", i))}
    
    # Permute LFC within module
    df_tmp <- df_de_res_all %>% 
        left_join(df_modules_filt) %>%
        filter(!is.na(Akula) & metric == "t_stat") %>% 
        group_by(module) %>%
        mutate(permuted_t = sample(Limma, replace = FALSE))
    
    # Calculate correlation between permuted data and Nirmala's LFC
    test <- cor.test(df_tmp$permuted_t, df_tmp$Akula)
    correlation <- test$estimate
    p_value <- test$p.value

    # Append to tibble
    df_limma_akula_cor_perm <- df_limma_akula_cor_perm %>% 
        bind_rows(
            tibble(
                perm = i,
                correlation = correlation,
                p_value = p_value
            )
        )
    
}

## Calculate permutation p-values
de_limma_akula_perm_p <- df_limma_akula_cor_perm %>% 
    mutate(obs_corr = cor.test(
        df_de_res_all %>% filter(!is.na(Akula) & metric == "t_stat") %>% pull(Limma), 
        df_de_res_all %>% filter(!is.na(Akula) & metric == "t_stat") %>% pull(Akula), 
        )$estimate
    ) %>%
    summarise(
        perm_p = (sum(abs(correlation) >= abs(obs_corr)) + 1) / (n_perm + 1)
    )
#Pperm=1*10^-4

```

```{r FigS9b.prep}
## Create df for plot
df_figS9b <- df_de_res_all %>% 
    
    # remove genes that were not included in Nirmala's analysis
    dplyr::filter(!is.na(Akula)) %>% 
    
    # normalize values to compare across analyses
    #mutate(akula = scale(akula), current = scale(current)) %>% 
    
    # add gene labels
    mutate(label = ifelse(abs(current) > 1.5 & abs(akula) > 1.5, gene_symbol, "")) %>% 
    
    # arrange to plot
    arrange(-abs(current))

```

```{r FigS9b.plot, fig.width = 4, fig.height = 2.25}
df_de_res_all %>% 
    #filter(metric == "l2fc") %>%
    #mutate(color = scale(Akula)[,1] + scale(Limma)[,1]) %>% 
    mutate(metric = ifelse(metric == "l2fc", "L2FC", "t-statistic")) %>% 
    
    ggplot(aes(x = Akula, y = Limma)) +
    geom_hline(yintercept = 0, color = "gray") +
    geom_vline(xintercept = 0, color = "gray") +
    geom_abline(lty = 2) +
    geom_point(color = "darkgray", size = 0.25) +
    # geom_text_repel(aes(label = label), min.segment.length = 0, max.overlaps = 15, size = 2.5) +
    geom_smooth(method = "lm", linewidth = 0.5, color = "maroon") +
    stat_cor(label.sep = "\n", size = 3, vjust = 1) +
    facet_wrap(vars(metric), scales = "free") +
    #scale_color_gradientn(colors = rev(brewer.rdbu(100)), guide = "none") +
    labs(
        x = "Akula DGE (DESeq2)", y = "Current study DGE (Limma-voom)",
        title = "B | Correlation between DGE analysis results"
    )
map(
  .x = c(".png", ".pdf"),
  .f = ~ ggsave(paste0(figures_dir, "S9B.DEG_correlation", .x), width = 4, height = 2.25)
)
```



