---
title: "Figure S5: WGCNA module characterization"
author: "Rachel Smith"
output: pdf_document
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(fig.width = 2.5, fig.height = 2, collapse = TRUE, warning = FALSE, message = FALSE, echo = FALSE)

## Set paths and load data
base_dir <- "~/Documents/PhD/projects/sgacc_wgcna_grcca/"
figures_dir <- paste0(base_dir, "outputs/updated_figures/figures/FigS5_6_moduleEigengeneRes/")
tables_dir <- paste0(base_dir, "outputs/updated_figures/tables/")
analysis_objects_dir <- paste0(base_dir, "outputs/updated_figures/objects/FigS5_6_moduleEigengeneRes/")

source(paste0(base_dir, "scripts/full_analysis_scripts/scripts/setup.R"))

## Load data objects for plots
objects <- list.files(analysis_objects_dir)
objects <- objects[!str_detect(objects, "null|archive")]
for (obj in objects){
  print(paste0("loading ", obj, "...."))
  load(paste0(analysis_objects_dir, obj))
}

## Load GO enrichment data
load(paste0(base_dir, "objects/", prefix, sep = "_", "SIGNED_SFT", soft_power, "_GO_RES.RDS")) # df_mods_go
```

### A | Modules significantly associated with SCZ per module eigengene analysis

```{r FigS5a.prep}
df_figS5a <- df_lm_dx %>% 
    dplyr::filter(p_value < 0.05 & term == "SCZ") %>% 
    unnest(cols = c(data)) %>% 
    mutate(label = case_when(
        dx == "SCZ" & p_value < 0.05 & p_adj > 0.05 ~ "*",
        dx == "SCZ" & p_value < 0.05 & p_adj < 0.05 ~ "**",
        TRUE ~ ""
    )
    )
```

```{r FigS5a.plot}
figS5a <- df_figS5a %>% 
    ggplot(aes(x = kme_resids, y = dx, color = dx, fill = dx)) +
    geom_point(position = position_jitter(width = 0.1), size = 0.5) +
    geom_boxplot(alpha = 0.1, outlier.shape = NA) +
    # geom_text(aes(label = label, x = -Inf), color = "black", size = 6,
    #           vjust = 0.75, hjust = -0.1, check_overlap = TRUE) +
    facet_wrap(vars(module), ncol = 1, scales = "free_x") +
    scale_fill_manual(values = dx_colors) +
    scale_color_manual(values = dx_colors) +
    labs(x = "kME (corrected for covariates)", y = NULL,
         #caption = "* = p < 0.05; ** = FDR < 0.05",
         title = "A | SCZ kME-diagnosis \nassociations"
    ) +
    theme(legend.position = "none",
          axis.text.y = element_text(size = 10)
    )
```

```{r FigS5a.save, fig.height = 5, fig.width = 2.5}
figS5a
map(
  .x = c(".png", ".pdf"),
  .f = ~ ggsave(paste0(figures_dir, "A.sig_SCZ_kME_modules", .x), width = fig_width, height = 5)
)
```

### B | Significant SCZ module enrichments

```{r FigS5b.prep}
data(stop_words)
vague_terms <- c("positive", "negative", "regulation", "response", "protein", "activity",
                 "pathway", "process", "involved", "signaling")

## Identify significant modules
sig_modules <- df_lm_dx %>% 
    dplyr::filter(p_value < 0.05 & term == "SCZ") %>% 
    pull(module)

# Filter for modules of interest
df_sig_go_res <- df_mods_go %>% 
    dplyr::filter(module %in% sig_modules)

## Identify top words in each significant (FDR < 0.05) module pathway
module_tokens_freq <- df_sig_go_res %>% 
    dplyr::filter(p.adjust < 0.05) %>% 
    group_by(module) %>% 
    unnest_tokens(word, Description) %>% 
    anti_join(stop_words) %>% 
    dplyr::filter(!(word %in% vague_terms)) %>% 
    dplyr::count(word, sort = TRUE)
```

```{r FigS5b.plot}
l_figS5b <- map(
    .x = as.character(sig_modules),
    .f = ~ module_tokens_freq %>% 
        dplyr::filter(module == .x) %>% 
        top_n(10, wt = n) %>% 
        ggplot(aes(label = word, size = n, color = module)) +
        geom_text_wordcloud() +
        facet_wrap(vars(module)) +
        scale_color_manual(values = module_colors) +
        scale_size_continuous(range = c(2.5, 5)) +
        theme_void() +
        theme(strip.text = element_blank(),
              plot.margin = margin(t = -75, r = -10, b = -75, l = -10)
        )
)
```

```{r FigS5b.save, fig.height = 5, fig.width = 2.5}
wrap_plots(l_figS5b, ncol = 1) & plot_annotation(title = "B | SCZ module enrichments")
map(
  .x = c(".png", ".pdf"),
  .f = ~ ggsave(paste0(figures_dir, "B.sig_SCZ_kME_modules", .x), width = fig_width, height = 5)
)
```

### S6 | WGCNA module enrichment for risk gene lists

```{r FigS6.prep}
df_figS6 <- df_mods_risk_gene_hypergeometric %>% 
    mutate(class = ifelse(str_detect(benchmark_list, "SCZ"), "SCZ", "other") %>% factor(levels = c("SCZ", "other"))) %>% 
    mutate(benchmark_list = str_remove_all(benchmark_list, "SCZ|\\)|\\(") %>% 
               str_trim %>% 
               str_replace(", ", ",\n")
    ) %>% 
    mutate(sig = case_when(p_adj < 0.001 ~ "***", p_adj < 0.01 ~ "**", p_adj < 0.05 ~ "*", TRUE ~ ""))
```

```{r FigS6.plot}
figS6 <- df_figS6 %>% 
    ggplot(aes(x = benchmark_list, y = module)) +
    geom_tile(aes(fill = module, alpha = -log10(p_adj))) +
    geom_text(aes(label = sig), size = 6, color = "black", vjust = 0.75) +
    facet_wrap(vars(class), scales = "free_x", nrow = 1) +
    scale_fill_manual(values = module_colors, guide = "none") +
    guides(alpha = guide_legend(title = "-log10(FDR)")) +
    labs(x = NULL, y = NULL, 
         title = "S6 | Risk gene list enrichment in WGCNA modules")
```

```{r figS6.save, fig.width = 4.5, fig.height= = 4}
figS6
map(
  .x = c(".png", ".pdf"),
  .f = ~ ggsave(paste0(figures_dir, "S6.risk_gene_module_hypergeometric", .x), width = 5, height = 4)
)
```


