---
title: "Figure 3: GRCCA results benchmarking & function enrichments"
author: "Rachel Smith"
output: pdf_document
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(fig.width = 2.5, fig.height = 2, collapse = TRUE, warning = FALSE, message = FALSE, echo = FALSE)

## Set paths and load data
base_dir <- "~/Documents/PhD/projects/sgacc_wgcna_grcca/"
figures_dir <- paste0(base_dir, "outputs/figures/Fig3_characterizeGRCCA/")
tables_dir <- paste0(base_dir, "outputs/tables/")
analysis_objects_dir <- paste0(base_dir, "outputs/objects/")

source(paste0(base_dir, "/scripts/load_WGCNA_res.R"))

## Load data objects for plots
objects <- list.files(analysis_objects_dir)
objects <- objects[!str_detect(objects, "null|archive")]
for (obj in objects){
  print(paste0("loading ", obj, "...."))
  load(paste0(analysis_objects_dir, obj))
}
```

### A | GRCCA results are significantly and specifically enriched for SCZ risk genes

```{r Fig3a.plot.top, fig.height = 2, fig.width = 2.5}
## Prep
df_fig3a_top <- df_grcca_fgsea_benchmark %>% 
    mutate(class = ifelse(str_detect(benchmark_list, "SCZ"), "SCZ", "other") %>% factor(levels = c("SCZ", "other"))) %>% 
    mutate(benchmark_list = str_remove_all(benchmark_list, "SCZ|\\)|\\(") %>% 
               str_trim %>% 
               str_replace(", ", ",\n")
    ) %>% 
    mutate(label_color = ifelse(padj < 0.05, "white", "black")) %>% 
    mutate(box_color = ifelse(padj < 0.05, "black", "transparent")) %>% 
    mutate(label = round(NES, 2) %>% format(digits = 3),
           label = ifelse(padj < 0.05, paste0(label, "*"), label)
    )
#mutate(sig = ifelse(padj < 0.05, scientific(padj, digits = 3), round(padj, 2) %>% format(digits = 3)))
   # mutate(sig = case_when(padj < 0.001 ~ "***", padj < 0.01 ~ "**", padj < 0.05 ~ "*", TRUE ~ ""))


## Plot
df_fig3a_top %>% 
    ggplot(aes(x = benchmark_list, y = 1)) +
    geom_tile(aes(fill = NES, color = I(box_color)), width = 0.95, height = 0.95, linewidth = 0.75) +
    geom_text(aes(label = label, color = I(label_color)), size = 3) +
    facet_wrap(vars(class), scales = "free", nrow = 2) +
    scale_fill_gradientn(colors = rev(brewer.rdbu(100)[1:50]), limits = c(1.0, 1.58)) +
    #scale_fill_gradientn(colors = rev(brewer.rdbu(100)), limits = c(-1.58, 1.58)) +
    guides(fill = guide_colorbar(title.hjust = 0.5, title.position = "left")) +
    labs(x = NULL, y = NULL,
         title = "A | Risk gene enrichment") +
    theme(axis.text.y = element_blank(),
          axis.ticks = element_blank(),
          axis.line = element_blank(),
          axis.text.x = element_text(margin = margin(t = -3)),
          strip.background = element_rect(fill = "white", color = "black"),
          legend.margin = margin(r = -15),
          legend.position = "left",
          legend.justification = "top",
          legend.title = element_text(angle = 90),
          legend.key.height = unit(0.75, "cm"),
          legend.key.width = unit(0.15, "cm")
    )


## Save
map(
  .x = c(".png", ".pdf"),
  .f = ~ ggsave(paste0(figures_dir, "Atop.Risk_gene_enrichment", .x), width = 2.5, height = 2)
)
```

```{r Fig3a.plot.bottom, fig.width = 1.3, fig.height = 1.3}
## Prep

# Identify genes to label in bottom panel
top_genes <- df_x_res %>% 
    dplyr::filter(ensembl_gene_id %in% benchmarking_lists[["SCZ (common, broad)"]]) %>% 
    top_n(n = 6, wt = abs(pearsons_r)) %>% 
    pull(ensembl_gene_id)

# Subset X res for genes in SCZ common broad list for bottom panel
df_fig3a_bottom <- df_x_res %>% 
    dplyr::filter(ensembl_gene_id %in% benchmarking_lists[["SCZ (common, broad)"]]) %>% 
    mutate(significant = ifelse(p_adj < 0.05, 1, 0) %>% factor) %>% 
    arrange(significant, abs(pearsons_r)) %>% 
    mutate(label = ifelse(ensembl_gene_id %in% top_genes, gene_symbol, ""))


## Plot
scale_max <- df_x_res %>% pull(pearsons_r) %>% abs %>% max
jitter_pos <- position_jitter(width = 0.1, seed = 123)
df_x_res %>%
    ggplot(aes(x = pearsons_r)) +
    geom_vline(xintercept = 0, color = "darkgrey") +
    geom_density() +
    geom_point(data = df_fig3a_bottom, 
               mapping = aes(x = pearsons_r, y = -0.5, fill = pearsons_r, color = significant), 
               pos = jitter_pos, shape = 21, size = 1
    ) +
    geom_text_repel(data = df_fig3a_bottom,
                    mapping = aes(x = pearsons_r, y = -0.5, label = label),
                    pos = jitter_pos, 
                    size = 2.5, box.padding = 0.75, max.overlaps = 100, force = 10, min.segment.length = 0
    ) +
    
    scale_fill_gradientn(colors = gene_weight_color_scale, limits = c(-scale_max, scale_max), guide = "none") +
    scale_color_manual(values = c("transparent", "black"), guide = "none") +
    labs(x = expression("Structure correlation (" * italic(r)[x] * ")"), y = NULL, 
         title = NULL) +
    theme(axis.text.y = element_blank(),
          axis.ticks.y = element_blank(),
          axis.text.x = element_text(size = 7),
          axis.title.x = element_text(size = 8),
          panel.border = element_rect(fill = "transparent", color = "black", size = 1),
          axis.line = element_blank()
    )

## Save
map(
  .x = c(".png", ".pdf"),
  .f = ~ ggsave(paste0(figures_dir, "Abottom.Risk_gene_enrichment", .x), width = 1.3, height = 1.3)
)
```


### B | GRCCA cell-type enrichments

```{r Fig3b.plot, fig.height = 2.25, fig.width = 2.5}
df_grcca_fgsea_cell %>% 
    mutate(sig = case_when(padj < 0.001 ~ "***", padj < 0.01 ~ "**", padj < 0.05 ~ "*", TRUE ~ "")) %>% 
    
    ggplot(aes(x = NES, y = reorder(cell_type, NES))) +
    geom_col(aes(fill = NES), color = "gray", shape = 21) +
    geom_text(aes(label = sig, x = NES), vjust = 0.75, size = 4, check_overlap = TRUE) +
    scale_fill_gradientn(colors = rev(brewer.rdbu(100)), limits = c(-3.39, 3.39)) +
    coord_cartesian(clip = "off") +
    labs(x = "NES", y = NULL,
         title = "B | Cell-type enrichment") +
    theme(legend.position = "none")
map(
  .x = c(".png", ".pdf"),
  .f = ~ ggsave(paste0(figures_dir, "B.cell_type_enrichment", .x), width = 2.5, height = 2.25)
)
```


### C | GRCCA GO enrichments

```{r Fig3c.prep}
## Determine labels
fig3c_labels <- c(
    "cilium movement",
    #"motile cilium",
    "axoneme",
    #"axonemal microtubule",
    #"axoneme assembly",
    "adaptive immune response",
    #"outer dynein arm assembly",
    "MHC class II protein complex",
    #"T cell costimulation",
    #"MHC class II protein complex binding",
    "minus-end-directed microtubule motor activity",
    "toll-like receptor signaling pathway",
    #"dynein light intermediate chain binding",

    "syntaxin-1 binding",
    #"ubiquitin-dependent protein catabolic process",
    #"endosome to lysosome transport",
    #"cytoplasmic translation",
    "regulation of autophagy",
    "postsynaptic density",
    "presynaptic endocytic zone membrane",
    "ATP binding",
    #"ATP hydrolysis activity",
    "protein ubiquitination"
)

## Filter for terms of interest & assign labels
df_fig3c <- df_grcca_fgsea_go %>% 
    dplyr::filter(padj < 0.05) %>% 
    mutate(direction = ifelse(NES < 0, "down", "up")) %>% 
    group_by(direction) %>% 
    mutate(label = ifelse(term %in% fig3c_labels, str_wrap(term, 25), ""))
```

```{r Fig3c.plot, fig.width = 6.5, fig.height = 4}
df_fig3c %>%
    ggplot(aes(x = padj, y = NES)) +
    geom_point(aes(size = size, fill = NES), color = "gray", shape = 21) +
    geom_text_repel(aes(label = label), size = 2.75, force = 20,
                    box.padding = 0.25, min.segment.length = 0, max.overlaps = 50) +
    geom_hline(yintercept = 0, color = "gray") +
    facet_wrap(vars(ontology)) +
    scale_fill_gradientn(colors = rev(brewer.rdbu(100)), limits = c(-3, 3), guide = "none") +
    scale_size_continuous(range = c(2, 6)) +
    scale_x_reverse(breaks = c(0, 0.03, 0.05)) +
    coord_cartesian(clip = "off") +
    guides(size = guide_legend(title = "n genes in path", title.hjust = 0.5, title.position = "top")) +
    labs(x = "Enrichment FDR", y = "NES",
         title = "C | Functional pathway enrichments") +
    theme(legend.position = "bottom",
          legend.justification = "center",
          title.justification = "center",
          legend.key.size = unit(0.3, "cm")
    )
map(
  .x = c(".png", ".pdf"),
  .f = ~ ggsave(paste0(figures_dir, "C.GO_enrichment", .x), width = 6.5, height = 4)
)
```

