---
title: "06e-00. Sensitivity analyses: Load gene-level RCCA results"
author: "Rachel Smith"
format: html
editor: visual
---

Load and process Regularized CCA (RCCA) results for sensitivity analysis.

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
base_dir <- "~/Documents/PhD/projects/sgacc_wgcna_grcca/"
```

## Setup

```{r load_data}
source(paste0(base_dir, "scripts/load_WGCNA_res.R"))
```

## Load data

```{r load_rcca}
## Identify CCA directory
n_mca_dim <- 8
type <- "GENES/"
project_dir <- paste0(
    prefix,
    "_sft", soft_power, "_minSize", minimum_size, "_cutHeight", tree_cut_height, "_",
    n_mca_dim, "MCA_regressBrainWeight_WITHGRAY/"
)
cca_dir <- paste0(base_dir, "RCCA_toolkit/", type, project_dir)

## Read in RCCA analysis results
analysis_type <- "rcca"
VARx <- "0.1_1"
l_rcca_res <- f_load_cca_res(
    cca_directory = cca_dir,
    level = "gene",
    analysis_type = analysis_type,
    mu = 0.1,
    VARx = VARx,
    include_Cmat = FALSE
)

## Assign results to tibbles; negate everything so SCZ is positive
df_results_rcca <- l_rcca_res$model_results
df_lvs_rcca <- l_rcca_res$latent_variables %>% mutate_at(vars(c(lvx, lvy)), ~ -.x)
df_y_res_rcca <- l_rcca_res$y_res %>% mutate_at(vars(c(weight, z_score, pearsons_r)), ~ -.x)
df_x_res_rcca <- l_rcca_res$x_res %>%
    mutate_at(vars(c(weight, z_score, pearsons_r)), ~ -.x) %>%
    left_join(df_ensembl_to_symbol) %>%
    left_join(df_modules_filt %>% dplyr::select(-c(mod_set, color)), by = join_by(ensembl_gene_id)) %>%
    dplyr::select(ensembl_gene_id, gene_symbol, module, everything()) %>%
    mutate(gene_symbol = ifelse(is.na(gene_symbol), ensembl_gene_id, gene_symbol))
```

## Save

```{r save}
# Figures
save(df_lvs_rcca, df_y_res_rcca, df_x_res_rcca,
    file = paste0(objects_dir, "RCCA_results.Rdata")
)
```
