---
title: "Figure S2: Drug Multiple Correspondence Analysis (MCA)"
author: "Rachel Smith"
output: pdf_document
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(fig.width = 2.5, fig.height = 2, collapse = TRUE, warning = FALSE, message = FALSE, echo = FALSE)

## Set paths and load data
base_dir <- "~/Documents/PhD/projects/sgacc_wgcna_grcca/"
figures_dir <- paste0(base_dir, "outputs/figures/supplement/")
tables_dir <- paste0(base_dir, "outputs/tables/")
analysis_objects_dir <- paste0(base_dir, "outputs/objects/supplement/")

source(paste0(base_dir, "sscripts/setup.R"))

## Load data objects for plots
objects <- list.files(analysis_objects_dir)
objects <- objects[!str_detect(objects, "null|archive")]
for (obj in objects){
  print(paste0("loading ", obj, "...."))
  load(paste0(analysis_objects_dir, obj))
}
```

### A | Matrix of drug use across 185 samples

```{r FigS2a.prep}
## Format drug names for publications
df_drugs_numeric <- df_covariates_numeric %>% 
  dplyr::select(sample, dx, all_of(drug_covariates)) %>% 
  
  # change drug names for figures
  dplyr::rename_all(~str_replace_all(.x, "anti_", "anti")) %>% 
  dplyr::rename_all(~str_replace_all(.x, "_", " ")) %>% 
  dplyr::rename(
    "nicotine/cotinine" =  "nicotine cotinine",
    "sedatives, hypnotics, anxiolitics" =  "sedative hypnotic anxiolitics",
    "major stimulants (cocaine included)" =  "major stimulants cocaine included",
    "benzodiazepines" = "benzos",
    "other psychotropic drug" = "other psychotropic drug"
  )

## Cluster samples to arrange for plot
samples_order <- df_drugs_numeric %>% 
  group_by(dx) %>% 
  nest() %>% 
  mutate(order = map(
    .x = data,
    .f = ~ .x %>% 
      column_to_rownames("sample") %>% 
      dist %>% 
      hclust %>% 
      .$order
  )) %>% 
  unnest(cols = c(data, order)) %>% 
  dplyr::select(dx, order, sample) %>% 
  mutate(dx = case_when(
    str_detect(sample, "control") ~ 1,
    str_detect(sample, "bipolar") ~ 2,
    str_detect(sample, "mdd") ~ 3,
    str_detect(sample, "schizo") ~ 4
  )) %>% 
  arrange(dx, order) %>% 
  pull(sample)

## Cluster drugs by sample use
drugs_order <- tibble(drug = df_drugs_numeric %>% dplyr::select(-sample, -dx) %>% colnames,
       order = df_drugs_numeric %>% 
         dplyr::select(-dx) %>% 
         column_to_rownames("sample") %>% 
         t() %>% 
         dist %>% 
         hclust %>% 
         .$order
) %>% 
  arrange(order) %>% 
  pull(drug)

## Format tibble with arrange rows & columns
df_figS2a <- df_drugs_numeric %>% 
    pivot_longer(3:ncol(.), names_to = "drug", values_to = "value") %>% 
    mutate(value = case_when(
        value == 1 ~ "detected/reported",
        value == 0 ~ "not detected/reported",
        is.na(value) ~ "unknown"
    ), 
    sample = factor(sample, levels = samples_order),
    drug = factor(drug, levels = drugs_order),
    dx = case_when(
        dx == 0 ~ "BD",
        dx == 1 ~ "Control",
        dx == 2 ~ "MDD",
        dx == 3 ~ "SCZ"
    ) %>% factor(levels = names(dx_colors))
    )

## Set matrix colors
matrix_colors <- c(
    "detected/reported" = "white",
    "not detected/reported" = "black",
    "unknown" = "gray"
)
```

```{r FigS2a.plot}
figS2a <- df_figS2a %>%
  ggplot(aes(x = sample)) +
  geom_tile(aes(y = drug, fill = value)) +
  geom_tile(aes(y = 0, fill = dx)) +
  geom_vline(xintercept = c(55.5, 90.5, 141.5), color = "maroon", linewidth = 0.75) +
  scale_fill_manual(values = c(matrix_colors, dx_colors),
                    na.value = "gray") +
  guides(fill = guide_legend(title = NULL)) +
  labs(y = NULL, title = "A | Drug use across 185 samples") +
  theme(axis.text.x = element_blank(),
        axis.ticks.x = element_blank(),
        legend.position = c(-0.7, 0.92),
        legend.key.size = unit(0.2, "cm"),
        legend.text = element_text(size = 8),
        axis.line = element_blank()
        )
```

```{r FigS2a.save, fig.height = 2.25, fig.width = 5}
figS2a
map(
  .x = c(".png", ".pdf"),
  .f = ~ ggsave(paste0(figures_dir, "A.drug_use_matrix", .x), width = 5, height = 2.25)
)
```

### B | Variance explained of each drug MCA dimension

```{r FigS2b.plot}
figS2b <- df_eig %>% 
    mutate(dim = factor(dim),
           label = paste0(round(cum_var, 2), "%")) %>% 
    
    ggplot(aes(x = dim)) +
    geom_col(aes(y = var, fill = var), color = "black") +
    #geom_point(aes(y = cum_var)) +
    # geom_text(aes(y = cum_var, label = label),
    #           size = 3, vjust = -1) +
    geom_hline(yintercept = 5, color = "maroon") +
    scale_fill_gradient(low = "white", high = "black", guide = "none") +
    labs(title = "B | MCA dimension \nvariance explained",
         x = "Dimension", y = "% variance explained") +
    theme(axis.text.x = element_text(angle = 45)
    )
```

```{r figS2b.save}
figS2b
map(
  .x = c(".png", ".pdf"),
  .f = ~ ggsave(paste0(figures_dir, "B.MCA_var_explained", .x), width = fig_width, height = fig_height)
)
```

### C | MCA dimension - covariate correlations

```{r FigS2c.prep}
## Set order
m_covariates <- df_covariates_numeric %>% column_to_rownames("sample") %>% t()
covariate_order <- m_covariates[hclust(dist(m_covariates))$order,] %>% rownames

## Arrange covariates and format for plotting
df_figS2c <- df_mca_covar_cor %>% 
    mutate(covariate = factor(covariate, levels = covariate_order),
           dimension = str_remove(dimension, "dim") %>% as.numeric %>% as.factor,
           #significant = ifelse(p_adj < 0.05, "yes", "no")
           significance = case_when(
               p_adj < 0.05 & p_adj > 0.01 ~ "*",
               p_adj < 0.01 & p_adj > 0.001 ~ "**",
               p_adj < 0.001 ~ "***",
               TRUE ~ ""
           )
    ) %>% 
    
    # remove technical covariates
    filter(!(covariate %in% technical_covariates))
```

```{r FigS2c.plot}
figS2c <- df_figS2c %>% 
    ggplot(aes(x = dimension, y = covariate)) +
    geom_tile(aes(fill = pearsons_r), linewidth = 0.5) +
    geom_text(aes(label = significance), vjust = 0.75, size = 2.5) +
    scale_fill_gradientn(colors = rev(brewer.rdbu(100)), limits = c(-1.0, 1.0)) +
    scale_color_manual(values = c("yes" = "black", "no" = "transparent"), guide = "none") +
    guides(fill = guide_colorbar(title = "Pearson's r", title.position = "left", title.hjust = 0.5)) +
    labs(x = "Dimension", y = NULL, 
         title = "C | MCA dimension correlations with \nknown covariates") +
    theme(legend.key.height = unit(1.5, "cm"),
          legend.key.width = unit(0.1, "cm"),
          legend.title = element_text(angle = 90),
          legend.margin = margin(l = -15)
    )
```

```{r FigS2c.save, fig.height = 5, fig.width = 5.5}
figS2c
map(
  .x = c(".png", ".pdf"),
  .f = ~ ggsave(paste0(figures_dir, "C.MCA_dimension_covariate_correlations", .x), width = 5.5, height = 5)
)
```

