---
title: "Figure 1: Study methods overview"
author: "Rachel Smith"
output: pdf_document
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(fig.width = 2.5, fig.height = 2, collapse = TRUE, warning = FALSE, message = FALSE, echo = FALSE)

## Set paths and load data
base_dir <- "~/Documents/PhD/projects/sgacc_wgcna_grcca/"
figures_dir <- paste0(base_dir, "outputs/updated_figures/figures/Fig1_analysisPipeline/")

source(paste0(base_dir, "scripts/full_analysis_scripts/scripts/load_WGCNA_res.R"))

## Load DE data
load(paste0(base_dir, "outputs/updated_figures/objects/Fig2_DGEres/DE_results.RDS")) # df_de_res
```

## 1. DE box plot

```{r Fig1.DEbox, fig.width = 1, fig.height = 1}
## Select gene for plotting
top_gene <- df_de_res %>% top_n(n = 1, wt = -stat) %>% pull(ensembl_gene_id)

## Plot
df_vsd_regress %>% 
    left_join(df_covariates) %>% 
    dplyr::select(dx, sample, all_of(top_gene)) %>% 
    filter(str_detect(sample, "schizo|control")) %>% 
    
    ggplot(aes(x = dx, y = get(top_gene), color = dx)) +
    geom_point(position = position_jitter(width = 0.2), size = 0.25) +
    geom_boxplot(fill = "transparent", outlier.shape = NA, width = 0.5) +
    scale_color_manual(values = dx_colors, guide = "none") +
    labs(x = NULL, y = NULL, title = NULL) +
    theme(
        axis.text = element_blank(),
        axis.ticks = element_blank()
    )

## Save
map(
  .x = c(".png", ".pdf"),
  .f = ~ ggsave(paste0(figures_dir, "1.DGE_boxplots", .x), width = 1, height = 1)
)

```

## 2. Volcano plot

```{r Fig1.volcano, fig.height = 1, fig.width = 1.25}
## Plot
df_de_res %>% 
    mutate(fill = ifelse(pvalue > 0.05, NA_real_, log2fold_change),
           significant = ifelse(ensembl_gene_id == top_gene, "yes", "no"),
           label = ifelse(ensembl_gene_id == top_gene, gene_symbol, "")
    ) %>% 
    
    ggplot(aes(x = log2fold_change, y = -log10(pvalue))) +
    geom_point(aes(fill = fill, color = significant), shape = 21, size = 0.75) +
    geom_hline(aes(yintercept = -log10(0.05)), linewidth = 0.25, color = "black") +
    geom_text_repel(aes(label = label), min.segment.length = 0, size = 2.25) +
    scale_fill_gradientn(colors = gene_weight_color_scale, 
                         values = rescale(c(-0.17, 0, 0.17)),
                         limits = c(-0.171, 0.171),
                         na.value = "lightgray", guide = "none") +
    scale_color_manual(values = c("yes" = "black", "no" = "transparent"), na.value = "transparent") +
    labs(x = NULL, y = NULL, title = NULL) +
    theme(
        axis.text = element_blank(),
        axis.ticks = element_blank(),
        legend.position = "none"
    )

## Save
map(
  .x = c(".png", ".pdf"),
  .f = ~ ggsave(paste0(figures_dir, "2.DGE_volcano", .x), width = 1.25, height = 1)
)
```

## 3. WGCNA dendrogram & colors

```{r Fig1.WGCNA, fig.height = 1}
## Convert regressed VSD counts to transposed matrix
m_vsd_regress <- df_vsd_regress %>% column_to_rownames("sample")

## Calculate co-expression similarity and adjacency
set.seed(20240306)
adjacency <- adjacency(m_vsd_regress, type = "signed hybrid", power = soft_power)

## Topological overlap matrix
doParallel::registerDoParallel()
set.seed(20240306)
TOM <- TOMsimilarity(adjacency, TOMType = "signed")
colnames(TOM) <- colnames(adjacency)
rownames(TOM) <- rownames(adjacency)
diag(TOM) <- NA

## Subset for plotting
baby_TOM <- TOM[1:1000, 1:1000]

## Set colors for annotation
annotation <- df_modules_filt %>% 
    dplyr::select(ensembl_gene_id, module) %>% 
    dplyr::filter(ensembl_gene_id %in% colnames(baby_TOM)) %>% 
    mutate(module = as.character(module)) %>% 
    mutate(ensembl_gene_id = factor(ensembl_gene_id, levels = colnames(baby_TOM))) %>% 
    arrange(ensembl_gene_id) %>% 
    column_to_rownames("ensembl_gene_id")
all(rownames(annotation) == rownames(baby_TOM))
module_colors <- df_modules_filt %>% 
    mutate(module = as.character(module)) %>% 
    dplyr::filter(ensembl_gene_id %in% colnames(baby_TOM)) %>% 
    dplyr::select(module, color) %>% 
    distinct %>% 
    deframe
annotation_col = list(module = module_colors)

## Plot
TOM_pheatmap <- pheatmap(
    mat = baby_TOM,
    color = colorRampPalette(c("white", "black"))(100),
    #color = colorRampPalette(brewer.pal(9, "YlOrRd"))(100),
    cluster_rows = FALSE,
    cluster_cols = TRUE,
    #annotation_row = annotation,
    annotation_col = annotation,
    annotation_colors = annotation_col,
    annotation_names_row = FALSE, 
    annotation_names_col = FALSE,
    border_color = NA,
    show_rownames = FALSE,
    show_colnames = FALSE,
    legend = FALSE,
    annotation_legend = FALSE
)

## Save
map(
  .x = c(".png", ".pdf"),
  .f = ~ ggsave(paste0(figures_dir, "3.WGCNA_dendrogram", .x), plot = TOM_pheatmap$gtable, width = fig_width, height = 1)
)
```

## 4. Dummy GSEA distribution

```{r Fig1.GSEA, fig.width = 2.5, fig.height = 2}
## Create dummy data for GSEA distribution
set.seed(124)
df_gsea_dummy <- tibble(
    dist = rnorm(n = 1000, mean = 0, sd = 1),
    points = rnorm(n = 1000, mean = 0.5, sd = .5)
)

## Plot
df_gsea_dummy %>% 
    ggplot() +
    geom_vline(xintercept = 0, color = "darkgrey") +
    geom_density(aes(x = dist)) +
    geom_point(mapping = aes(x = points, y = -0.1, color = points), 
               pos = position_jitter(height = 0.085), size = 0.75
    ) +
    scale_color_gradientn(colors = gene_weight_color_scale, limits = c(-2.2, 2.2), guide = "none") +
    labs(x = NULL, y = NULL, title = NULL) +
    theme(axis.text = element_blank(),
          axis.ticks = element_blank(),
          legend.position = "none"
    )

## Save
map(
  .x = c(".png", ".pdf"),
  .f = ~ ggsave(paste0(figures_dir, "4.GSEA_dist", .x), width = fig_width, height = fig_height)
)
```

## 5. Dummy risk gene correlation

```{r Fig1.riskGene}

```

