---
title: "Figure 2: GRCCA results"
author: "Rachel Smith"
output: pdf_document
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(fig.width = 2.5, fig.height = 2, collapse = TRUE, warning = FALSE, message = FALSE, echo = FALSE)

## Set paths and load data
base_dir <- "~/Documents/PhD/projects/sgacc_wgcna_grcca/"
figures_dir <- paste0(base_dir, "outputs/figures/Fig2_GRCCAres/")
tables_dir <- paste0(base_dir, "outputs/tables/")
analysis_objects_dir <- paste0(base_dir, "outputs/objects/Fig2_GRCCAres/")

source(paste0(base_dir, "scripts/full_analysis_scripts/scripts/load_WGCNA_res.R"))

## Load data objects for plots
objects <- list.files(analysis_objects_dir)
objects <- objects[!str_detect(objects, "null|archive")]
for (obj in objects){
  print(paste0("loading ", obj, "...."))
  load(paste0(analysis_objects_dir, obj))
}

## Load DE res (to compare to GRCCA)
load(paste0(base_dir, "objects/DE_results.RDS")) # df_de_res
```

### A | Model results

```{r Fig2a.plot}
fig2a <- df_results %>% 
    mutate(significant = ifelse(pval == 0.001, "yes", "no")) %>% 
    ggplot(aes(x = factor(varx*100), y = -log10(pval))) +
    geom_segment(aes(y = 0, yend = -log10(pval))) +
    geom_point(aes(size = correl, shape = significant, fill = -log10(pval))) +
    geom_hline(yintercept = 0, color = "darkgrey") +
    scale_shape_manual(values = c("yes" = 23, "no" = 21), guide = "none") +
    scale_fill_gradient(low = "white", high = "#67001F", limits = c(0, 3), guide = "none") +
    guides(size = guide_legend(title = "X-Y LV correlation", override.aes = list(shape = 21))) +
    coord_cartesian(clip = "off") +
    labs(x = "X variance explained (%)", y = "-log10(model p-value)",
         title = "A | Optimal variance explained \nby model"
    ) +
    theme(
        legend.position = c(0.075, 0.6),
        legend.key.size = unit(0.1, "cm")
    )
```

```{r Fig2a.save, fig.width = 2.5}
fig2a
map(
  .x = c(".png", ".pdf"),
  .f = ~ ggsave(paste0(figures_dir, "A.optimal_var_explained", .x), width = fig_width, height = fig_height)
)
```

### B | Covariate (Y) structure correlations

```{r Fig2b.plot}
fig2b <- df_y_res %>% 
    mutate(significant = ifelse(abs(z_score) >= 2 & p_adj < 0.05, "*", "")) %>% 
    
    ggplot(aes(x = pearsons_r, y = reorder(covariate, pearsons_r))) +
    geom_point(aes(size = -log10(p_adj), fill = pearsons_r), shape = 21) +
    geom_vline(xintercept = 0, color = "darkgrey") +
    geom_text(aes(label = significant), size = 6, vjust = 0.75, hjust = -1.5, color = "black") +
    scale_fill_gradientn(colors = gene_weight_color_scale, limits = c(-1, 1), guide = "none") +
    scale_size_continuous(range = c(2, 6)) +
    guides(size = guide_legend(title = "-log10(FDR)")) +
    coord_cartesian(clip = "off") +
    xlim(c(-1, 1)) +
    labs(y = NULL, x = expression("Structure correlation (" * italic(r)[y] * ")"), 
         title = "B | Covariate structure correlations") +
    theme(legend.position = c(0.68, 0.35), 
          legend.box = "horizontal",
          #legend.justification = "center",
          #legend.key.size = unit(0.2, 'cm')
          legend.key.height = unit(0.29, "cm"),
          legend.key.width = unit(0.30, "cm")
    )
```

```{r Fig2b.save, fig.width = 4.0}
fig2b
map(
  .x = c(".png", ".pdf"),
  .f = ~ ggsave(paste0(figures_dir, "B.covariate_structCor", .x), width = 4.0, height = fig_height)
)
```

### C | Top n genes (X) by structure correlation

```{r Fig2c.prep}
df_fig2c <- df_x_res %>% 
    dplyr::filter(p_adj < 0.05 & abs(z_score) >= 2) %>%
    top_n(n = 20, wt = abs(pearsons_r)) %>%
    mutate(direction = ifelse(pearsons_r < 0, "2neg", "1pos"))
```

```{r Fig2c.plot}
fig2c <- df_fig2c %>% 
    ggplot(aes(x = pearsons_r, y = reorder(gene_symbol, pearsons_r))) +
    geom_point(aes(size = -log10(p_adj), fill = pearsons_r), shape = 21) +
    geom_vline(xintercept = 0, color = "darkgrey") +
    facet_wrap(vars(direction), ncol = 1, scales = "free_y") +
    force_panelsizes(rows = c(16, 4)) +
    scale_fill_gradientn(colors = gene_weight_color_scale, 
                         limits = c(-0.57, 0.57), guide = "none") +
    scale_size_continuous(range = c(2, 5)) +
    guides(size = guide_legend(title = "-log10(FDR)")) +
    xlim(c(-1, 1)) +
    coord_cartesian(clip = "off") +
    labs(y = NULL, x = expression("Structure correlation (" * italic(r)[x] * ")"), 
         title = "C | Top 20 genes by \nstructure correlation"
    ) +
    theme(strip.text = element_blank(), 
          panel.spacing = unit(2, "lines"),
          legend.position = c(0.05, 0.7), 
          legend.box = "horizontal",
          legend.key.size = unit(0.35, "cm")
    )
```

```{r Fig2c.save, fig.height = 4}
fig2c
map(
  .x = c(".png", ".pdf"),
  .f = ~ ggsave(paste0(figures_dir, "C.gene_structCor", .x), width = fig_width, height = 4)
)
```

### D | Expression directions of top positively- and negatively-weighted genes

```{r Fig2d.prep}
top_pos_gene <- df_x_res %>% dplyr::filter(pearsons_r > 0) %>% arrange(-abs(pearsons_r)) %>% head(1) %>% pull(ensembl_gene_id) # BCL7A
top_neg_gene <- df_x_res %>% dplyr::filter(pearsons_r < 0) %>% arrange(-abs(pearsons_r)) %>% head(1) %>% pull(ensembl_gene_id) # CFAP46
df_fig2d <- df_vsd_regress %>% 
    dplyr::select(sample, all_of(c(top_neg_gene, top_pos_gene))) %>% 
    pivot_longer(contains("ENSG"), names_to = "ensembl_gene_id", values_to = "expr") %>% 
    left_join(df_ensembl_to_symbol) %>% 
    mutate(dx = case_when(
        str_detect(sample, "control") ~ "Control",
        str_detect(sample, "bipolar") ~ "BD",
        str_detect(sample, "mdd") ~ "MDD",
        str_detect(sample, "schizo") ~ "SCZ"
    ) %>% 
        factor(levels = names(dx_colors)))
```

```{r Fig2d.stats}
load(paste0(base_dir, "objects/DE_results.RDS")) # df_de_res
df_de_res %>% dplyr::filter(ensembl_gene_id %in% c(top_pos_gene, top_neg_gene))
```

```{r Fig2d.plot}
fig2d <- df_fig2d %>% 
    ggplot(aes(x = dx, y = expr)) +
    geom_point(aes(color = dx), position = position_jitter(width = 0.2), size = 0.5) +
    geom_boxplot(aes(color = dx, fill = dx), alpha = 0.1, outlier.shape = NA) +
    geom_hline(yintercept = 0, color = "darkgrey") +
    facet_wrap(vars(gene_symbol), scales = "free_y", nrow = 1) +
    #force_panelsizes(cols = c(1, 1)) +
    scale_fill_manual(values = dx_colors, guide = "none") +
    scale_color_manual(values = dx_colors, guide = "none") +
    labs(x = NULL, y = "Corrected expression value",
         title = "D | Gene expression values") +
    theme(axis.text.x = element_text(angle = 45, hjust = 0.9))
```

```{r Fig2d.save, fig.width = 4.0}
fig2d
map(
  .x = c(".png", ".pdf"),
  .f = ~ ggsave(paste0(figures_dir, "D.top_gene_expression_values", .x), width = 4, height = fig_height)
)
```

### E | GRCCA structure correlations (r) as they relate to expression values

```{r Fig2e.prep}
df_fig2e <- df_vsd_regress %>% 
    pivot_longer(contains("ENSG"), names_to = "ensembl_gene_id", values_to = "expression_value") %>% 
    mutate(dx = case_when(
        str_detect(sample, "control") ~ "Control",
        str_detect(sample, "bipolar") ~ "BD",
        str_detect(sample, "mdd") ~ "MDD",
        str_detect(sample, "schizo") ~ "SCZ"
    ) %>% factor(levels = names(dx_colors))) %>% 
    group_by(ensembl_gene_id, dx) %>% 
    summarise(mean_expr = mean(expression_value)) %>% 
    left_join(df_x_res)
```

```{r Fig2e.plot}
fig2e <- df_fig2e %>% 
    ggplot(aes(x = mean_expr, y = pearsons_r)) +
    geom_hline(yintercept = 0, color = "gray") +
    geom_vline(xintercept = 0, color = "gray") +
    geom_point(color = "black", size = 0.25) +
    geom_smooth(aes(color = dx), method = "lm", linewidth = 0.75) +
    stat_cor(aes(label = after_stat(r.label), color = dx), label.sep = "\n", size = 3,
             label.y.npc = "top", hjust = -0.1, vjust = -1.75, face = "bold") +
    facet_wrap(vars(dx), nrow = 1) +
    scale_color_manual(values = dx_colors) +
    scale_x_continuous(breaks = c(-0.4, 0, 0.4)) +
    coord_cartesian(clip = "off") +
    labs(x = "Mean expression (corrected)", y = expression("Structure correlation (" * italic(r)[x] * ")"),
         title = "E | Relationship between gene \nstructure correlation & expression"
    ) +
    theme(legend.position = "none")
```

```{r Fig2e.save, fig.width = 4.0}
fig2e
map(
  .x = c(".png", ".pdf"),
  .f = ~ ggsave(paste0(figures_dir, "E.gene_strucCor_vs_Expr", .x), width = 4.0, height = fig_height)
)
```
