---
title: "Figure 5: GRCCA transcript-level results"
author: "Rachel Smith"
output: pdf_document
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(fig.width = 2.5, fig.height = 2, collapse = TRUE, warning = FALSE, message = FALSE, echo = FALSE)

## Set paths and load data
base_dir <- "~/Documents/PhD/projects/sgacc_wgcna_grcca/"
figures_dir <- paste0(base_dir, "outputs/figures/Fig5_GRCCAtranscriptsRes/")
tables_dir <- paste0(base_dir, "outputs/tables/")
analysis_objects_dir <- paste0(base_dir, "outputs/objects/Fig5_GRCCAtranscriptsRes/")

source(paste0(base_dir, "scripts/full_analysis_scripts/scripts/setup.R"))

## Load data objects for plots
objects <- list.files(analysis_objects_dir)
objects <- objects[!str_detect(objects, "null|archive")]
for (obj in objects){
  print(paste0("loading ", obj, "...."))
  load(paste0(analysis_objects_dir, obj))
}

## Load GRCCA results (in Fig2_GRCCAres)
load(paste0(analysis_objects_dir, "../Fig2_GRCCAres/GRCCA_results.Rdata")) # df_x_res
df_x_res_genes <- df_x_res
rm(list = "df_x_res")
```

### A | Covariate structure correlations (ry)

```{r Fig5a.plot}
fig5a <- df_y_res_transcripts %>% 
    mutate(significant = ifelse(abs(z_score) >= 2 & p_adj < 0.05, "*", "")) %>% 
    
    ggplot(aes(x = pearsons_r, y = reorder(covariate, pearsons_r))) +
    geom_vline(xintercept = 0, color = "darkgrey") +
    geom_point(aes(size = -log10(p_adj), fill = pearsons_r), shape = 21) +
    #geom_text(aes(label = significant), size = 6, vjust = 0.75, hjust = -1.5, color = "black") +
    scale_fill_gradientn(colors = gene_weight_color_scale, limits = c(-1, 1), guide = "none") +
    scale_size_continuous(range = c(2, 6)) +
    guides(size = guide_legend(title = "-log10(FDR)")) +
    coord_cartesian(clip = "off") +
    xlim(c(-1, 1)) +
    labs(y = NULL, x = expression("Structure correlation (" * italic(r)[y] * ")"), 
         title = "A | Covariate structure correlations") +
    theme(legend.position = c(0.04, 0.55), 
          legend.box = "horizontal",
          #legend.justification = "center",
          #legend.key.size = unit(0.2, 'cm')
          legend.key.size = unit(0.1, "cm")
    )
```

```{r Fig5a.save, fig.width = 2.5}
fig5a
map(
  .x = c(".png", ".pdf"),
  .f = ~ ggsave(paste0(figures_dir, "A.covariate_structCor", .x), width = fig_width, height = fig_height)
)
```

### B | Correlation with gene-level GRCCA results

```{r Fig5b.prep}
## Identify all SCZ risk genes across lists
scz_risk_genes <- benchmarking_lists[names(benchmarking_lists)[str_detect(names(benchmarking_lists), "SCZ")]] %>% 
    unlist %>% 
    unique

## Write function to calculate distance from point to line
f_distance_to_line <- function(x, y, m, b) {
    abs(m * x - y + b) / sqrt(m^2 + 1)
}

## Combine gene & transcript-level gene weights, highlight SCZ risk genes for plot
df_fig5b <- df_x_res_transcripts %>% 
    #filter(!is.na(ensembl_gene_id)) %>% 
    group_by(ensembl_gene_id) %>% 
    summarise(pearsons_r = max(pearsons_r)) %>% 
    #summarise(pearsons_r = ifelse(pearsons_r < 0, min(pearsons_r), max(pearsons_r))) %>% 
    dplyr::rename("transcript_res" = "pearsons_r") %>% 
    
    left_join(df_x_res_genes %>% 
                  dplyr::select(ensembl_gene_id, gene_symbol, pearsons_r) %>% 
                  dplyr::rename("gene_res" = "pearsons_r")
    ) %>% 
    
    # calculate distance to y = x
    mutate(distance = f_distance_to_line(gene_res, transcript_res, 1, 0)) %>%
    
    # highlight SCZ risk genes
    mutate(
        risk_gene = ifelse(ensembl_gene_id %in% scz_risk_genes, "yes", "no"),
        label = ifelse(risk_gene == "yes" & distance < 0.1 & abs(gene_res) > 0.1, gene_symbol, "")
    ) %>% 
    arrange(risk_gene)
```

```{r Fig5b.plot}
fig5b <- df_fig5b %>% 
    #filter(risk_gene == "yes") %>% 
    
    ggplot(aes(x = gene_res, y = transcript_res)) +
    geom_abline(lty = 2) +
    geom_vline(xintercept = 0, color = "gray") +
    geom_hline(yintercept = 0, color = "gray") +
    geom_point(aes(fill = gene_res + transcript_res, color = risk_gene, size = risk_gene), shape = 21) +
    geom_text_repel(aes(label = label), size = 2.5, max.overlaps = 100, min.segment.length = 0) +
    stat_cor(size = 2.5) +
    geom_smooth(method = "lm", color = "black", linewidth = 0.5) +
    guides(color = guide_legend(title = "SCZ risk gene?")) +
    xlim(c(-0.6, 0.6)) +
    ylim(c(-0.6, 0.6)) +
    scale_fill_gradientn(colors = gene_weight_color_scale, guide = "none") +
    scale_color_manual(values = c("yes" = "black", "no" = "transparent")) +
    scale_size_manual(values = c("yes" = 0.75, "no" = 0.25), guide = "none") +
    labs(x = expression("Gene " * italic(r)[x]), y = expression("Transcript " * italic(r)[x]),
         title = "B | Gene vs transcript GRCCA results") +
    theme(legend.position = c(0.55, 0.15),
          legend.key.size = unit(0.1, "cm"),
          legend.title = element_text(size = 8),
          legend.text = element_text(size = 6)
    )
```

```{r Fig5b.save, fig.width = 2.5}
fig5b
map(
  .x = c(".png", ".pdf"),
  .f = ~ ggsave(paste0(figures_dir, "B.gene_vs_transcript_GRCCA_res", .x), width = fig_width, height = fig_height)
)
```

### C | Directionality of transcripts associated with significant and non-significant risk genes

```{r Fig5c.prep}
## Select illustrative genes to plot
fig5c_sig_genes <- c(        
    "FMNL1", # sig, one transcript
    "C3", # sig, subset of transcripts,
    "EZH1" # sig, many transcripts
)
fig5c_non_sig_genes <- c(
    "PLCL2", # non sig, 0 transcripts
    "TMEM127", # non-sig, opposite directions
    "CDK14" # non-sig, opposite directions
)

## Set order
fig5c_gene_order <- df_x_res_genes %>% 
    filter(gene_symbol %in% c(fig5c_sig_genes, fig5c_non_sig_genes)) %>% 
    arrange(-abs(pearsons_r)) %>% 
    pull(gene_symbol)

## Prep df for plotting
df_fig5c <- df_x_res_transcripts %>% 
    filter(gene_symbol %in% fig5c_gene_order) %>% 
    mutate(
        gene_symbol = factor(gene_symbol, levels = fig5c_gene_order),
        significant = ifelse(p_adj < 0.05, "yes", "no"),
        gene_sig = ifelse(gene_symbol %in% fig5c_sig_genes, "significant", "non-significant")
    )
```

```{r Fig5c.function}
f_plot_fig5c <- function(df, gene_level_sig, max_color_scale = 1) {
    df %>% 
        filter(gene_sig == gene_level_sig) %>% 
        
        ggplot(aes(x = pearsons_r, y = reorder(transcript_symbol, pearsons_r))) +
        geom_vline(xintercept = 0, color = "gray") +
        geom_point(aes(fill = pearsons_r, size = -log10(p_adj), color = significant), shape = 21) +
        facet_wrap(vars(gene_symbol), scales = "free_y") +
        scale_fill_gradientn(colors = gene_weight_color_scale, limits = c(-max_color_scale, max_color_scale), guide = "none") +
        scale_color_manual(values = c("yes" = "black", "no" = "gray"), guide = "none") +
        scale_size_continuous(range = c(1, 4)) +
        guides(size = guide_legend(title = "-log10(FDR)")) +
        coord_cartesian(clip = "off") +
        labs(x = expression("Transcript " * italic(r)[x]), y = NULL)
}
```

```{r Fig5c.plot}
fig5c_sig <- f_plot_fig5c(df_fig5c, gene_level_sig = "significant", max_color_scale = 0.457) +
    labs(title = "Significant")
fig5c_non_sig <- f_plot_fig5c(df_fig5c, gene_level_sig = "non-significant", max_color_scale = 0.146) +
    labs(title = "Non-significant")
```

```{r Fig5b.save, fig.width = 6, fig.height = 4.25}
fig5c_sig / fig5c_non_sig
map(
  .x = c(".png", ".pdf"),
  .f = ~ ggsave(paste0(figures_dir, "C.directionality_of_transcripts", .x), width = 6, height = 4.25)
)
```


############ OTHER GENES TO PLOT? ##############

```{r}
genes_to_plot <- c("AKAP9", "NRXN1", "DCTN2", "EHBP1", "KIF1B", "SMARCE1", "TCF4", "AKT3", "GRIN1", "FMNL1", "RBFOX1")
genes_to_plot <- c("NRXN1", "GRIN1", "FMNL1", "RBFOX1", "C3", "PKN2-AS1")
genes_to_plot <- c("NSF", "KANSL1", "CRHR1", "ARHGAP27", "LRRC37A", "CCDC43", "FMNL1", 
                   "SPPL2C", "MAPT", "PLEKHM1", "STH", "LINC002210-CRHR1") # Eva's paper
genes_to_plot <- c("ZNF804A") # Owen et al 2023
#genes_to_plot <- benchmarking_lists[["SCZ (rare)"]]
p <- df_x_res_transcripts %>% 
    #filter(ensembl_gene_id %in% benchmarking_lists[["SCZ (rare)"]]) %>% 
    filter(gene_symbol %in% genes_to_plot) %>%
    #filter(ensembl_gene_id %in% intersect(sig_risk_genes, more_than_one_transcript)) %>%
    mutate(
        #gene_symbol = factor(gene_symbol, levels = sig_risk_gene_order),
        significant = ifelse(p_adj < 0.05, "yes", "no")
    ) %>% 
    
    ggplot(aes(x = pearsons_r, y = reorder(ensembl_transcript_id, pearsons_r))) +
    geom_vline(xintercept = 0, color = "gray") +
    geom_point(aes(fill = pearsons_r, size = -log10(p_adj), color = significant), shape = 21) +
    facet_wrap(vars(gene_symbol), scales = "free_y") +
    scale_fill_gradientn(colors = gene_weight_color_scale) +
    scale_color_manual(values = c("yes" = "black", "no" = "gray")) +
    coord_cartesian(clip = "off")
df_x_res_genes %>% filter(gene_symbol %in% genes_to_plot)
df_de_res %>% filter(gene_symbol %in% genes_to_plot)
```

